version: 0.2
env:
  variables:
    RDS_HOST: ${codepipeline.RDS_HOST}
    RDS_DB_NAME: ${codepipeline.RDS_DB_NAME}
    RDS_USER: ${codepipeline.RDS_USER}
    RDS_PASSWORD: ${codepipeline.RDS_PASSWORD}
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo ${RDS_DB_NAME}
  build:
    commands:
      - python -m pytest --junitxml=tests/test-report tests/tests.py
reports:
  pytest_reports:
    files:
      - test-report
    base-directory: tests
    file-format: JUNITXML