version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
      - python -m pytest --junitxml=tests/test-report tests/tests.py
reports:
  pytest_reports:
    files:
      - test-report
    base-directory: tests
    file-format: JUNITXML